Enterprise Application/Controllers/PaymentRecordController.cs
using Enterprise.Entity;
using Enterprise.Service;
using Enterprise_Application.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RotativaCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Enterprise_Application.Controllers
{
    [Authorize(Roles = "Admin , Manager")]
    public class PaymentRecordController : Controller
    {
        private readonly IPayComputeService _paymentRecord;
        private readonly IEnterpriseService _enterpriseService;
        private readonly INationalInsuranceComputation _nationalInsuranceComputation1;
        private readonly ITaxComputation _taxComputation1;
        private decimal OverTimes;
        private decimal OverTimesEarning;
        private decimal ContratualEarning;
        private decimal TotalAmount;
        private decimal union;
        private decimal tax;
        private decimal TotalDeduction;

        public decimal Nlc { get; private set; }
        public decimal SLC { get; private set; }

        public PaymentRecordController(IPayComputeService payComputeService, 
            IEnterpriseService enterpriseService,
            INationalInsuranceComputation nationalInsuranceComputation,
            ITaxComputation taxComputation)
        {
            _paymentRecord = payComputeService;
            _enterpriseService = enterpriseService;
            _nationalInsuranceComputation1 = nationalInsuranceComputation;
            _taxComputation1 = taxComputation;
            
        }
        public IActionResult Index(int? PageNumber)
        {
            var PayMent = _paymentRecord.GetAll().Select(Pay => new PaymentRecordIndexViewModel
            {
                Id = Pay.Id,
                EmployeeId = Pay.EmployeeId,
                FullName = Pay.FullName,
                PayDate = Pay.PaymentDay,
                PayMonth = Pay.PaymentMonth,
                TaxYearId = Pay.TaskYearId,
                Year = _paymentRecord.GetTaxById(Pay.TaskYearId).YearOfTax,
                TotalDeduction = Pay.TotalDeduction,
                TotalEarning = Pay.TotalEarning,
                Employee = Pay.Employee,
                Net = Pay.TotalEarning,
            }).ToList();
            int PageSize = 5;
            return View(PaymentRecordListPagination<PaymentRecordIndexViewModel>.Create(PayMent, PageSize ,PageNumber??1));
        }
        [HttpGet]
     [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
          ViewBag.EmployeeId = _paymentRecord.GetAllEmployeesPayRow();
          ViewBag.TaxYearId = _paymentRecord.GetAllTaxYear(); 
          var CreateView = new PaymentRecordCreateViewModel();
          return View(CreateView);
        }
       
        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult>Create(PaymentRecordCreateViewModel paymentRecord)
        {
            if (ModelState.IsValid)
            {
                var Payment = new PaymentRecord()
                {
                    Id = paymentRecord.Id,
                    EmployeeId = paymentRecord.EmployeeId,
                    FullName = _enterpriseService.GetAsyncById(paymentRecord.EmployeeId).FullName,
                    NiNo = _enterpriseService.GetAsyncById(paymentRecord.EmployeeId).NationalInsuranceNumber,
                    PaymentDay = paymentRecord.PaymentDay,
                    TaskYearId = paymentRecord.TaskYearId,
                    TaskCode = paymentRecord.TaskCode,
                    HourlyWorked = paymentRecord.HourlyWorked,
                    HourlyRate = paymentRecord.HourlyRate,
                    ContratualHour = paymentRecord.ContratualHour,
                    OvertimeEarning = OverTimesEarning = _paymentRecord.OverTimeEarnings(_paymentRecord.OverTimeRate(paymentRecord.HourlyRate), OverTimes),
                    ContratualEarning = ContratualEarning = _paymentRecord.ContratualEarnings(paymentRecord.ContratualHour, paymentRecord.HourlyWorked, paymentRecord.HourlyRate),
                    OvertimeHour = OverTimes = _paymentRecord.OverTimeHours(paymentRecord.HourlyWorked, paymentRecord.ContratualHour),
                    SLc = SLC = _enterpriseService.StudentLoanRefundPayment(paymentRecord.EmployeeId, TotalAmount),
                    NLC = Nlc =  _nationalInsuranceComputation1.NLcAmount(TotalAmount),
                    UnionFee = union = _enterpriseService.UnionFee(paymentRecord.EmployeeId),
                    Tax = tax = _taxComputation1.TaxAmount(TotalAmount),
                    TotalDeduction =TotalDeduction = _paymentRecord.TotalDeduction(tax,SLC,Nlc,union),
                    TotalEarning = TotalAmount = _paymentRecord.TotalEarning(OverTimesEarning, ContratualEarning),
                    NetPayment = _paymentRecord.Netpay(TotalAmount, TotalDeduction),
                };
               await _paymentRecord.CreateAsync(Payment);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.EmployeeId = _paymentRecord.GetAllEmployeesPayRow();
            ViewBag.TaxYearId = _paymentRecord.GetAllTaxYear();
            return View();
        }
        public IActionResult Details(int id)
        {
            var paymentRecord = _paymentRecord.GetById(id);
            if (paymentRecord == null)
            {
                return NotFound();
            }
            var DetailView = new PaymentDetailViewModel
            {
                Id = paymentRecord.Id,
                EmployeeId = paymentRecord.EmployeeId,
                FullName = paymentRecord.FullName,
                NiNo = paymentRecord.NiNo,
                NLC = paymentRecord.NLC,
                PayDate = paymentRecord.PaymentDay,
                TaskYearId = paymentRecord.TaskYearId,
                Year = _paymentRecord.GetTaxById(paymentRecord.TaskYearId).YearOfTax,
                TaskCode = paymentRecord.TaskCode,
                HourlyWorked = paymentRecord.HourlyWorked,
                HourlyRate = paymentRecord.HourlyRate,
                ContratualHour = paymentRecord.ContratualHour,
                TotalDeduction = paymentRecord.TotalDeduction,
                TotalEarning = paymentRecord.TotalEarning,
                NetPayment = paymentRecord.NetPayment,
                PayMonth = paymentRecord.PaymentMonth,
                OvertimeEarning = paymentRecord.OvertimeEarning,
                OvertimeHour = paymentRecord.OvertimeHour,
                OverTimeRate = _paymentRecord.OverTimeRate(paymentRecord.HourlyRate),
                ContratualEarning = paymentRecord.ContratualEarning,
                UnionFee = paymentRecord.UnionFee,
                Tax = paymentRecord.Tax,
                SLc = paymentRecord.SLc,

            };
            return View(DetailView);
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult PaySlip(int id)
        {
            var paymentRecord = _paymentRecord.GetById(id);
            if(paymentRecord == null)
            {
                return NotFound();
            }
            var DetailView = new PaymentDetailViewModel
            {
                Id = paymentRecord.Id,
                EmployeeId = paymentRecord.EmployeeId,
                FullName = paymentRecord.FullName,
                NiNo = paymentRecord.NiNo,
                NLC = paymentRecord.NLC,
                PayDate = paymentRecord.PaymentDay,
                TaskYearId = paymentRecord.TaskYearId,
                Year = _paymentRecord.GetTaxById(paymentRecord.TaskYearId).YearOfTax,
                TaskCode = paymentRecord.TaskCode,
                HourlyWorked = paymentRecord.HourlyWorked,
                HourlyRate = paymentRecord.HourlyRate,
                ContratualHour = paymentRecord.ContratualHour,
                TotalDeduction = paymentRecord.TotalDeduction,
                TotalEarning = paymentRecord.TotalEarning,
                NetPayment = paymentRecord.NetPayment,
                PayMonth = paymentRecord.PaymentMonth,
                OvertimeEarning = paymentRecord.OvertimeEarning,
                OvertimeHour = paymentRecord.OvertimeHour,
                OverTimeRate = _paymentRecord.OverTimeRate(paymentRecord.HourlyRate),
                ContratualEarning = paymentRecord.ContratualEarning,
                UnionFee = paymentRecord.UnionFee,
                Tax = paymentRecord.Tax,
                SLc = paymentRecord.SLc,

            };
            return View(DetailView);
        }
        public  IActionResult Print(int id)
        {
            var PrintPdf = new ActionAsPdf("PaySlip", new { Id = id })
            {
                FileName = "PaySlip.pdf",

            };
            return PrintPdf;
        }
      
       
    }
}

Enterprise Application/Views/PaymentRecord/Create.cshtml
@model PaymentRecordCreateViewModel
@{
    ViewBag.Title = "New Pay";
}
<div class="container">
    <div class="col-12 grid-margin-md-12 stretch-card">
        <div class="card">
            <div class="card-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
                        <li class="breadcrumb-item" aria-current="page">New Pay</li>
                    </ol>
                </nav>
                <br /><br />
                <form method="post" enctype="multipart/form-data" asp-action="Create">
                    <div asp-validation-summary="ModelOnly"></div>

                    <div class="form-group">

                       <select  asp-for="EmployeeId" asp-items=" ViewBag.EmployeeId" class="form-control">
                            <option selected>Select Employee</option>
                        </select>
                        <span asp-validation-for="EmployeeId" class="text-danger"></span>
                    </div><br /><br />

                    <div class="form-row">
                        <div class="form-group col-md-1">
                            <label asp-for="TaskYearId"></label>
                        </div>
                        <div class="form-group col-md-3">
                            <select asp-for="TaskYearId" asp-items="ViewBag.TaxYearId" class="form-control">
                                <option selected>Select Tax Year</option>
                            </select>
                            <span asp-validation-for="TaskYearId" class="text-danger"></span>
                        </div>
                       
                        <div class="form-group col-md-1">
                            <label asp-for="PaymentDay"></label>
                        </div>
                        <div class="form-group col-md-3">
                            <input asp-for="PaymentDay" class="form-control" />
                            <span asp-validation-for="PaymentDay" class="text-danger"></span>
                        </div>
                      
                        <div class="form-group-col-md-1">
                            <label asp-for="PaymentMonth"></label>
                        </div>
                        <div class="form-group-col-md-3">
                            <select asp-for="PaymentMonth" class="form-control">
                                <option selected>Select Month</option>
                                <option>January</option>
                                <option>Febuary</option>
                                <option>March</option>
                                <option>April</option>
                                <option>May</option>
                                <option>June</option>
                                <option>July</option>
                                <option>August</option>
                                <option>September</option>
                                <option>Octobar</option>
                                <option>Novermber</option>
                                <option>December</option>

                            </select>
                            <span asp-validation-for="PaymentMonth" class="text-danger"></span>
                        </div>
                      
                        <div class="form-row">
                            <div class="form-group col-md-1">
                                <label asp-for="HourlyWorked"></label>
                            </div>
                            <div class="form-group col-md-3">
                                <input asp-for=" HourlyWorked" class="form-control" />
                                <span asp-validation-for="HourlyWorked" class="text-danger"></span>
                            </div>
                           
                            <div class="form-group col-md-1">
                                <label asp-for="HourlyRate"></label>
                            </div>
                            <div class="form-group col-md-3">
                                <input asp-for=" HourlyRate" class="form-control" />
                                <span asp-validation-for="HourlyRate" class="text-danger"></span>
                            </div>
                           
                            <div class="form-group col-md-1">
                                <label asp-for="ContratualHour"></label>
                            </div>
                            <div class="form-group col-md-3">
                                <input asp-for=" ContratualHour" class="form-control" readonly style="background-color:#293043" />

                            </div>
                        </div>
                    </div><br /><br />
                    <div class="form-group">
                        <button type="submit" class="btn btn-rounded float-left btn btn-primary"><i class="fa fa-save"><l style="margin-left:7px">Save</l></i></button>
                        <a class="btn btn-rounded btn btn-success float-right" asp-action="Index" asp-controller="PaymentRecord"><i class="fa-solid fa-backward"><l style="margin-left:7px">Back</l></i></a>
                    </div>
                </form>

            </div>
            <br /><br /><br /><br /><br /> 
        </div>

    </div>
</div>
@section Scripts{ 
@{await (Html.RenderPartialAsync("_ValidationScriptsPartial"));
}
}

Enterprise Application/Views/PaymentRecord/Details.cshtml
@model PaymentDetailViewModel
<div class="container">
    <div class="col-md-12 grid-margin-md-0 stretch-card">
        <div class="card">
            <div class="card-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a asp-action="index" asp-controller="Home">Home</a></li>
                        <li class="breadcrumb-item"><a asp-action="index" asp-controller="PaymentRecord">Pay Record</a></li>
                        <li class="breadcrumb-item">Details</li>
                    </ol>
                </nav>
                <br />
                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label asp-for="FullName"></label>
                    </div>
                    <div class="form-group col-md-4 font-italic font-weight-bold">
                        <input asp-for="FullName" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-2">
                        <label asp-for="NiNo"></label>
                    </div>
                    <div class="form-group col-md-4">
                        <input asp-for="NiNo" class="form-control" readonly style="background-color:#293043" />
                    </div>

                </div>
                <br /><br />
                <h3>Date|Hour</h3>
                <hr style="background-color:darkred" />
                <br />
                <div class="form-row">

                    <div class="form-group col-md-1">
                        <label asp-for="PayDate"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="PayDate" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-1">
                        <label asp-for="PayMonth"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="PayMonth" class="form-control" readonly style="background-color:#293043" />
                    </div>

                    <div class="form-group col-md-1">
                        <label asp-for="Year"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="Year" class="form-control" readonly style="background-color:#293043" />
                    </div>

                </div>
                <div class="form-row">

                    <div class="form-group col-md-1">
                        <label asp-for="HourlyWorked"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="HourlyWorked" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-1">
                        <label asp-for="HourlyRate"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="HourlyRate" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-1">
                        <label asp-for="ContratualHour"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="ContratualHour" class="form-control" readonly style="background-color:#293043" />
                    </div>
                </div><br /><br />
                <h3>Deduction</h3>
                <hr style="background-color:darkred" />

                <div class="form-row">

                    <div class="form-group col-md-1">
                        <label asp-for="TaskCode"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="TaskCode" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-1">
                        <label asp-for="Tax"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="Tax" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-1">
                        <label asp-for="SLc"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="SLc" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-1">
                        <label asp-for="UnionFee"></label>
                    </div>
                    <div class="form-group col-md-3 col-md-offset-3">
                        <input asp-for="UnionFee" class="form-control" readonly style="background-color:#293043" />
                    </div>
                </div>
                <br />
                <h3>Earnings</h3>
                <hr style="background-color:darkred" />

                <div class="form-row">

                    <div class="form-group col-md-1">
                        <label asp-for="TotalEarning"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="TotalEarning" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-1">
                        <label asp-for="TotalDeduction"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="TotalDeduction" class="form-control" readonly style="background-color:#293043" />
                    </div>
                    <div class="form-group col-md-1">
                        <label asp-for="NetPayment"></label>
                    </div>
                    <div class="form-group col-md-3">
                        <input asp-for="NetPayment" class="form-control" readonly style="background-color:#293043" />
                    </div>

                </div><br />
                <div class="form-group">
                    <a class="btn btn-success btn btn-rounded" asp-action="Index" asp-controller="PaymentRecord"><i class="fa-solid fa-backward"><l style="margin-left:7px"></l></i>Back</a>
                </div>
            </div>
            <br /><br /><br /><br /> <br />
        </div>
    </div>

Enterprise Application/Views/PaymentRecord/Index.cshtml
@model PaymentRecordListPagination<PaymentRecordIndexViewModel>
@{
    ViewBag.title = "Payment Record";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Payment Record</li>
                        </ol>
                    </nav>
                    <br />
                    <br />
                    <div class="row">
                        <div class="col-md-12 table-responsive-md">
                            <h4>Payment Record</h4>
                            <a class="btn btn-success float-right" asp-action="Create">New pay</a>
                            <br />
                            <br />
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <td>
                                            Employee
                                        </td>
                                        <td>
                                            Pay Date
                                        </td>
                                        <td>
                                            pay Month

                                        </td>
                                        <td>
                                            Tax Year
                                        </td>
                                        <td>
                                            Total Earning
                                        </td>
                                        <td>
                                            Tax Deduction
                                        </td>
                                        <td>
                                            Net Payment
                                        </td>
                                        <td class="text-warning" style="width:130px">
                                            Action
                                        </td>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td><a asp-action="details" asp-route-id="@item.Id">@item.FullName</a></td>
                                            <td>@item.PayDate.ToString("dd/mm/yyyy")</td>
                                            <td>@item.PayMonth.ToString("MMMM")</td>
                                            <td>@item.Year</td>
                                            <td>@item.TotalEarning.ToString("c")</td>
                                            <td>@item.TotalDeduction.ToString("c")</td>
                                            <td>@item.Net.ToString("c")</td>
                                            <td>
                                                <a class="text-primary" asp-action="Payslip" asp-controller="PaymentRecord" asp-route-id="@item.Id">Preview Payslip</a>
                                                <a class="text-info " asp-action="Print" asp-controller="PaymentRecord" asp-route-id="@item.Id"><i class="fas fa-file-pdf"><l style="margin-left:7px">Pdf</l></i></a>

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <br /><br /><br />
                            @{
                                var DisablePrevious = !Model.IsPreviousPageAvailabe ? "disabled" : "";
                                var DisableNext = !Model.IsNextPageAvailable ? "disabled" : "";

                            }
                            <a asp-action="Index" asp-route-PageNumber="@(Model.PageIndex - 1)" class="btn btn-primary @DisablePrevious">Previous</a>
                            <a asp-action="Index" asp-route-PageNumber="@(Model.PageIndex + 1)" class="btn btn-primary @DisableNext">Next</a>
                        </div>
                    </div>
                </div>
                <br />
                <br /><br /><br />
            </div>
        </div>
    </div>


</div>

Enterprise Application/Views/PaymentRecord/PaySlip.cshtml
@model PaymentDetailViewModel
@{
    ViewBag.title = "Pay Slip";
    Layout = null;
}
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card-body">
            <div class="container-fluid d-flex justify-content-between flex-wrap">
                <div class="col-md-3 pl-0">
                   <img src="~/Image/Project pictures/Hicad (2).png"/><p style="font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">Hicad PayRoll System</p>
                
                    <p class="mt-5 mb-2"><b>Hicad System Ltd</b></p>
                    <p>134 Ajao Estate off Airport Road<br />Lagos Nigeria</p>
                </div>
                <div class="col-md-3 pr-0">
                    <p class="mt-5 mb-2 text-right">Pay Date:@Model.PayDate.ToString("dd/mm/yyyy")</p>
                    <p class="text-right">Tax Code:@Model.TaskCode<br />Year: @Model.Year<br />HRMC</p>
                </div>
            </div>
            <br /><br />
            <div class="col-md-12 row">
                <div class="col-md-8">Employee Name:@Model.FullName</div>
                <div class="col-md-4">National Insurance Number:@Model.NiNo</div>

            </div>
            <br /><br />
            <div class="row">
                <div class="col-md-12 table-responsive-md">
                    <table class="table table-striped">
                        <thead class="table-dark">
                            <tr>
                                <th>
                                    Earnings
                                </th>
                                <th>
                                    Hours
                                </th>
                                <th>
                                    Rate
                                </th>

                                <th>
                                    Amount
                                </th>
                                <th>
                                    Deduction
                                </th>
                                <th>
                                    Amount
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Basic:</td>
                                <td>@Model.ContratualHour.ToString("f")</td>
                                <td>@Model.HourlyRate.ToString("f")</td>
                                <td>@Model.ContratualEarning.ToString("C")</td>
                                <td>Tax:</td>
                                <td>@Model.Tax.ToString("f")</td>
                            </tr>
                            <tr>
                                <td>OverTime:</td>
                                <td>@Model.OvertimeHour.ToString("f")</td>
                                <td>@Model.OverTimeRate.ToString("f")</td>
                                <td>@Model.OvertimeEarning.ToString("C")</td>
                                <td>SLC:</td>
                                <td>@Model.SLc.Value.ToString("c")</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td> </td>
                                <td>NLC:</td>
                                <td>@Model.NLC.ToString("c")</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td> </td>
                                <td>Union Fee:</td>
                                <td>@Model.UnionFee.Value.ToString("f")</td>
                            </tr>

                            <tr>
                                <td>Total:</td>
                                <td>@Model.HourlyWorked</td>
                                <td></td>
                                <td>@Model.TotalEarning.ToString("c") </td>
                                <td></td>
                                <td>@Model.TotalDeduction.ToString("C")</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td class="table-dark"><b>Net Pay</b></td>
                                <td class="table-dark"><b>@Model.NetPayment.ToString("C")</b></td>
                            </tr>
                        </tbody>

                    </table>
                </div>

            </div>

        </div>
    </div>

</div>